### PR TITLE
Let player's leave their islands without override perm.

### PR DESCRIPTION
**Pull request by Time6628**

### CODE REVIEW

**Comment by KaiKikuchi** [comment]
Why did you add something unrelated to the merge pull request?

**Comment by Time6628** [comment]
DIdn't mean to put that into the pull, added it to our fork to let players know how to add people to their islands :P.

**Comment by KaiKikuchi** [comment]
Actually the invite command thing wasn't a bad idea. But I would do this: instead of informing the player about the trust command, the /is invite command can run the /trust command for them, and send a message to the invited player.

**Comment by Time6628** [comment]
I'll do that when I get a chance, and make the pull :cat:

**Comment by KaiKikuchi** [comment]
Thank you!

**Pull request closed without merging**
